### ISSUE TITLE
compile error - use Matrix3 and not Matrix4

### ISSUE THREAD

**Issue by cborelc** [movAX13h/Zwerg#1]
Hi:
I was getting compile errors in lines 297, 298,... in MainForm.cs:
argument 2 cannot convert from 'opentk.matrix4' to 'opentk.matrix3'

I just changed all the Matrix4 to Matrix3 and it works now.

Great little editor!

PS: I was not able to get the binary to run either - this is the error - I copied opengl32.dll to the zwerg directory:

System.EntryPointNotFoundException: Unable to find an entry point named 'glCreateShader' in DLL 'opengl32.dll'.
   at OpenTK.Graphics.OpenGL.GL.Core.CreateShader(ShaderType type)
   at OpenTK.Graphics.OpenGL.GL.CreateShader(ShaderType type)
   at Core.Shader.Compile()
   at Zwerg.MainForm.loadShader()
   at Zwerg.MainForm.glControl1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by movAX13h** [comment]
I've fixed this now in the latest release. OpenTK is now updated via NuGet.
